### ISSUE TITLE
pin typecheck dependencies

### ISSUE THREAD

**Issue by jakkdl** [python-trio/flake8-async#197]
libcst+pyright just started going crazy on me. So need to add pinning (+ autoupdating) for the typecheck dependencies too

**Comment by Zac-HD** [comment]
`libcst` shipped a new version last night, with fixes for some hints - bet that's the problem 😅

**Comment by jakkdl** [comment]
That sounds about right ... except the CI machines aren't getting any errors?? And even when I run `pyright` manually with a lower `libcst` version it's failing on my end (I even tried a fresh clone, no change)

**Comment by jakkdl** [comment]
This should also be resolved with pre-commit updates running regularly catching problems as they pop up.
