### ISSUE TITLE
Extend ASYNC110 to also warn if looping a `checkpoint()`

### ISSUE THREAD

**Issue by jakkdl** [python-trio/flake8-async#201]
There being two sleep-related confusions can plausibly cause a bit of confusion, this code will raise TRIO115 (replace `sleep(0)` with checkpoint) and TRIO110 (replace looped sleep with an Event)
```
while foo():
  await trio.sleep(0)
```
but if the user resolves the ASYNC115, then ASYNC110 will also stop warning. I don't think it's something super common, but it happened in https://github.com/python-trio/trio/pull/2947#pullrequestreview-1873485506 - so plausibly might happen again.

**Comment by Zac-HD** [comment]
Yeah, makes sense - `while ...: checkpoint()` is pretty inefficient so hopefully it's also rare, but that's even more reason to add it to the rule 👍
