### ISSUE TITLE
Add lint error for _any_ `except` block that might raise

### ISSUE THREAD

**Issue by Zac-HD** [python-trio/flake8-async#262]
c.f. https://github.com/python-trio/trio/issues/455#issuecomment-2135987009 - this would be similar to `ASYNC102` but I think ideally a separate rule so that people who wish to disable this (if lost exceptions aren't a big deal for them) don't reintroduce lost _cancellations_.

We should probably also do something similar for `__aexit__` methods, although this gets increasingly awkward for `@asynccontextmanager` functions and so that should probably be a further separate rule.

**Comment by jakkdl** [comment]
`__aexit__` seems straightforward, we just treat the content of the whole method as if it's a `finally:`, and can probably use `ASYNC102` for it.
For `@asynccontextmanager`, 102/120 should already cover if the yield is inside a `try:` - so I think that should maybe have an entirely separate rule for `yield-in-async-cm-not-in-try`?

**Comment by jakkdl** [comment]
with #307 closed this is now fully addressed once #306 is merged
